import { Geist, Geist_Mono, Inter, Space_Grotesk  } from "next/font/google";
import { AuthProvider } from '@/context/FirebaseAuthContext';
import "./globals.css";
import {UserProvider} from "@/context/UserContext";
import AOSProvider from "@/lib/AOSProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${spaceGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <UserProvider>
            <AOSProvider>
              {children}
            </AOSProvider>
          </UserProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
